/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Raffle.types";
import * as _1 from "./Raffle.client";
import * as _2 from "./Raffle.message-composer";
import * as _3 from "./NFTLoan.types";
import * as _4 from "./NFTLoan.client";
import * as _5 from "./NFTLoan.message-composer";
export namespace contracts {
  export const Raffle = { ..._0,
    ..._1,
    ..._2
  };
  export const NFTLoan = { ..._3,
    ..._4,
    ..._5
  };
}