/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  deposit_collaterals: {
    comment?: string | null;
    loan_preview?: AssetInfo | null;
    terms?: LoanTerms | null;
    tokens: AssetInfo[];
  };
} | {
  modify_collaterals: {
    comment?: string | null;
    loan_id: number;
    loan_preview?: AssetInfo | null;
    terms?: LoanTerms | null;
  };
} | {
  withdraw_collaterals: {
    loan_id: number;
  };
} | {
  make_offer: {
    borrower: string;
    comment?: string | null;
    loan_id: number;
    terms: LoanTerms;
  };
} | {
  cancel_offer: {
    global_offer_id: string;
  };
} | {
  refuse_offer: {
    global_offer_id: string;
  };
} | {
  withdraw_refused_offer: {
    global_offer_id: string;
  };
} | {
  accept_offer: {
    global_offer_id: string;
  };
} | {
  accept_loan: {
    borrower: string;
    comment?: string | null;
    loan_id: number;
  };
} | {
  repay_borrowed_funds: {
    loan_id: number;
  };
} | {
  withdraw_defaulted_loan: {
    borrower: string;
    loan_id: number;
  };
} | {
  set_owner: {
    owner: string;
  };
} | {
  set_fee_distributor: {
    fee_depositor: string;
  };
} | {
  set_fee_rate: {
    fee_rate: Decimal;
  };
};
export type AssetInfo = {
  cw721_coin: Cw721Coin;
} | {
  sg721_token: Sg721Token;
} | {
  coin: Coin;
};
export type Uint128 = string;
export type Decimal = string;
export interface Cw721Coin {
  address: string;
  token_id: string;
}
export interface Sg721Token {
  address: string;
  token_id: string;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface LoanTerms {
  duration_in_blocks: number;
  interest: Uint128;
  principle: Coin;
}
export interface InstantiateMsg {
  deposit_fee_amount: number;
  deposit_fee_denom: string[];
  fee_distributor: string;
  fee_rate: Decimal;
  name: string;
  owner?: string | null;
}
export type QueryMsg = {
  config: {};
} | {
  borrower_info: {
    borrower: string;
  };
} | {
  collateral_info: {
    borrower: string;
    loan_id: number;
  };
} | {
  collaterals: {
    borrower: string;
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  all_collaterals: {
    limit?: number | null;
    start_after?: [string, number] | null;
  };
} | {
  offer_info: {
    global_offer_id: string;
  };
} | {
  offers: {
    borrower: string;
    limit?: number | null;
    loan_id: number;
    start_after?: string | null;
  };
} | {
  lender_offers: {
    lender: string;
    limit?: number | null;
    start_after?: string | null;
  };
};